export enum ProviderType {
  BAILEYS = 'BAILEYS',
  META_WHATSAPP_CLOUD = 'META_WHATSAPP_CLOUD',
  META_INSTAGRAM = 'META_INSTAGRAM',
  META_MESSENGER = 'META_MESSENGER',
  TWILIO_SMS = 'TWILIO_SMS',
  TWILIO_WHATSAPP = 'TWILIO_WHATSAPP',
  TWILIO_VOICE = 'TWILIO_VOICE',
  TWILIO_VERIFY = 'TWILIO_VERIFY',
}

export enum ProviderChannel {
  WHATSAPP = 'WHATSAPP',
  SMS = 'SMS',
  MMS = 'MMS',
  INSTAGRAM_DM = 'INSTAGRAM_DM',
  MESSENGER = 'MESSENGER',
  VOICE = 'VOICE',
  VERIFY = 'VERIFY',
}

export enum ProviderCapability {
  SEND_TEXT = 'SEND_TEXT',
  SEND_IMAGE = 'SEND_IMAGE',
  SEND_VIDEO = 'SEND_VIDEO',
  SEND_AUDIO = 'SEND_AUDIO',
  SEND_DOCUMENT = 'SEND_DOCUMENT',
  SEND_STICKER = 'SEND_STICKER',
  SEND_LOCATION = 'SEND_LOCATION',
  SEND_CONTACTS = 'SEND_CONTACTS',
  SEND_TEMPLATE = 'SEND_TEMPLATE',
  SEND_INTERACTIVE_BUTTONS = 'SEND_INTERACTIVE_BUTTONS',
  SEND_INTERACTIVE_LIST = 'SEND_INTERACTIVE_LIST',
  SEND_REACTION = 'SEND_REACTION',
  SEND_REPLY = 'SEND_REPLY',
  MARK_READ = 'MARK_READ',
  TYPING_INDICATOR = 'TYPING_INDICATOR',
  UPLOAD_MEDIA = 'UPLOAD_MEDIA',
  DOWNLOAD_MEDIA = 'DOWNLOAD_MEDIA',
  TEMPLATE_MANAGEMENT = 'TEMPLATE_MANAGEMENT',
  MAKE_CALL = 'MAKE_CALL',
  VERIFY_OTP = 'VERIFY_OTP',
}

export const PROVIDER_CHANNEL_BY_TYPE: Readonly<Record<ProviderType, ProviderChannel>> = Object.freeze({
  [ProviderType.BAILEYS]: ProviderChannel.WHATSAPP,
  [ProviderType.META_WHATSAPP_CLOUD]: ProviderChannel.WHATSAPP,
  [ProviderType.META_INSTAGRAM]: ProviderChannel.INSTAGRAM_DM,
  [ProviderType.META_MESSENGER]: ProviderChannel.MESSENGER,
  [ProviderType.TWILIO_SMS]: ProviderChannel.SMS,
  [ProviderType.TWILIO_WHATSAPP]: ProviderChannel.WHATSAPP,
  [ProviderType.TWILIO_VOICE]: ProviderChannel.VOICE,
  [ProviderType.TWILIO_VERIFY]: ProviderChannel.VERIFY,
});
